[2025-06-14T21:43:20.970+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-14T21:43:20.976+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:38:16.431329+00:00 [queued]>
[2025-06-14T21:43:20.979+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:38:16.431329+00:00 [queued]>
[2025-06-14T21:43:20.979+0100] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-14T21:43:20.986+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_small_dataset> on 2025-06-14 20:38:16.431329+00:00
[2025-06-14T21:43:20.988+0100] {standard_task_runner.py:64} INFO - Started process 118159 to run task
[2025-06-14T21:43:20.989+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_churn_training_dag', 'train_small_dataset', 'manual__2025-06-14T20:38:16.431329+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpr96x8h2r']
[2025-06-14T21:43:20.990+0100] {standard_task_runner.py:91} INFO - Job 29: Subtask train_small_dataset
[2025-06-14T21:43:21.011+0100] {task_command.py:426} INFO - Running <TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:38:16.431329+00:00 [running]> on host neonm.
[2025-06-14T21:43:21.040+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_churn_training_dag' AIRFLOW_CTX_TASK_ID='train_small_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T20:38:16.431329+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T20:38:16.431329+00:00'
[2025-06-14T21:43:21.041+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-14T21:43:21.041+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-14T21:43:21.042+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python ../../scripts/model_training.py --dataset data/small_dataset.csv --n_estimators 150 --max_depth 8 --mlflow_uri http://127.0.0.1:5000']
[2025-06-14T21:43:21.045+0100] {subprocess.py:86} INFO - Output:
[2025-06-14T21:43:21.051+0100] {subprocess.py:93} INFO - python: can't open file '/tmp/airflowtmp7zrv6y5d/../../scripts/model_training.py': [Errno 2] No such file or directory
[2025-06-14T21:43:21.052+0100] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-14T21:43:21.052+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-14T21:43:21.054+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-14T21:43:21.056+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=customer_churn_training_dag, task_id=train_small_dataset, run_id=manual__2025-06-14T20:38:16.431329+00:00, execution_date=20250614T203816, start_date=20250614T204320, end_date=20250614T204321
[2025-06-14T21:43:21.062+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task train_small_dataset (Bash command failed. The command returned a non-zero exit code 2.; 118159)
[2025-06-14T21:43:21.082+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-14T21:43:21.089+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-14T21:43:21.092+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
