[2025-06-14T22:32:28.722+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-14T22:32:28.729+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_on_full_dataset manual__2025-06-14T21:30:20.409329+00:00 [queued]>
[2025-06-14T22:32:28.732+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_on_full_dataset manual__2025-06-14T21:30:20.409329+00:00 [queued]>
[2025-06-14T22:32:28.732+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-14T22:32:28.739+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_on_full_dataset> on 2025-06-14 21:30:20.409329+00:00
[2025-06-14T22:32:28.742+0100] {standard_task_runner.py:64} INFO - Started process 147061 to run task
[2025-06-14T22:32:28.744+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_churn_training_dag', 'train_on_full_dataset', 'manual__2025-06-14T21:30:20.409329+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpw4obuggt']
[2025-06-14T22:32:28.745+0100] {standard_task_runner.py:91} INFO - Job 67: Subtask train_on_full_dataset
[2025-06-14T22:32:28.762+0100] {task_command.py:426} INFO - Running <TaskInstance: customer_churn_training_dag.train_on_full_dataset manual__2025-06-14T21:30:20.409329+00:00 [running]> on host neonm.
[2025-06-14T22:32:28.794+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_churn_training_dag' AIRFLOW_CTX_TASK_ID='train_on_full_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T21:30:20.409329+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T21:30:20.409329+00:00'
[2025-06-14T22:32:28.794+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-14T22:32:28.795+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-14T22:32:28.799+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /home/press/coding/acronis_interview_v02 &&             python scripts/model_training.py                 --data_path kaggle_datasets/telecom_customer_churn.csv                 --n_estimators 100                 --max_depth 10                 --top_n_features 20                 --mlflow_tracking_uri http://127.0.0.1:5000\n        ']
[2025-06-14T22:32:28.803+0100] {subprocess.py:86} INFO - Output:
[2025-06-14T22:32:35.833+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-14T22:32:35.835+0100] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 147061. PIDs of all processes in the group: [147062, 147063, 147061]
[2025-06-14T22:32:35.835+0100] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 147061
[2025-06-14T22:32:35.835+0100] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-14T22:32:35.835+0100] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-06-14T22:32:35.836+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-14T22:32:35.841+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-14T22:32:35.842+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=customer_churn_training_dag, task_id=train_on_full_dataset, run_id=manual__2025-06-14T21:30:20.409329+00:00, execution_date=20250614T213020, start_date=20250614T213228, end_date=20250614T213235
