[2025-06-14T21:47:00.393+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-14T21:47:00.399+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:41:55.884545+00:00 [queued]>
[2025-06-14T21:47:00.402+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:41:55.884545+00:00 [queued]>
[2025-06-14T21:47:00.402+0100] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-14T21:47:00.408+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_small_dataset> on 2025-06-14 20:41:55.884545+00:00
[2025-06-14T21:47:00.410+0100] {standard_task_runner.py:64} INFO - Started process 120082 to run task
[2025-06-14T21:47:00.412+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_churn_training_dag', 'train_small_dataset', 'manual__2025-06-14T20:41:55.884545+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp58dcmkjj']
[2025-06-14T21:47:00.413+0100] {standard_task_runner.py:91} INFO - Job 32: Subtask train_small_dataset
[2025-06-14T21:47:00.432+0100] {task_command.py:426} INFO - Running <TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:41:55.884545+00:00 [running]> on host neonm.
[2025-06-14T21:47:00.460+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_churn_training_dag' AIRFLOW_CTX_TASK_ID='train_small_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T20:41:55.884545+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T20:41:55.884545+00:00'
[2025-06-14T21:47:00.461+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-14T21:47:00.461+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-14T21:47:00.462+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python ../../scripts/model_training.py --dataset data/small_dataset.csv --n_estimators 150 --max_depth 8 --mlflow_uri http://127.0.0.1:5000']
[2025-06-14T21:47:00.465+0100] {subprocess.py:86} INFO - Output:
[2025-06-14T21:47:00.470+0100] {subprocess.py:93} INFO - python: can't open file '/tmp/airflowtmpks8wq4d6/../../scripts/model_training.py': [Errno 2] No such file or directory
[2025-06-14T21:47:00.471+0100] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-14T21:47:00.471+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-14T21:47:00.474+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-14T21:47:00.475+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=customer_churn_training_dag, task_id=train_small_dataset, run_id=manual__2025-06-14T20:41:55.884545+00:00, execution_date=20250614T204155, start_date=20250614T204700, end_date=20250614T204700
[2025-06-14T21:47:00.481+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task train_small_dataset (Bash command failed. The command returned a non-zero exit code 2.; 120082)
[2025-06-14T21:47:00.504+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-14T21:47:00.511+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-14T21:47:00.515+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
