[2025-06-14T21:45:11.563+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-14T21:45:11.570+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:40:07.071750+00:00 [queued]>
[2025-06-14T21:45:11.572+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:40:07.071750+00:00 [queued]>
[2025-06-14T21:45:11.572+0100] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-14T21:45:11.579+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_small_dataset> on 2025-06-14 20:40:07.071750+00:00
[2025-06-14T21:45:11.581+0100] {standard_task_runner.py:64} INFO - Started process 119031 to run task
[2025-06-14T21:45:11.583+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_churn_training_dag', 'train_small_dataset', 'manual__2025-06-14T20:40:07.071750+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpej0fh9qt']
[2025-06-14T21:45:11.584+0100] {standard_task_runner.py:91} INFO - Job 30: Subtask train_small_dataset
[2025-06-14T21:45:11.605+0100] {task_command.py:426} INFO - Running <TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:40:07.071750+00:00 [running]> on host neonm.
[2025-06-14T21:45:11.638+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_churn_training_dag' AIRFLOW_CTX_TASK_ID='train_small_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T20:40:07.071750+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T20:40:07.071750+00:00'
[2025-06-14T21:45:11.639+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-14T21:45:11.639+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-14T21:45:11.640+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python ../../scripts/model_training.py --dataset data/small_dataset.csv --n_estimators 150 --max_depth 8 --mlflow_uri http://127.0.0.1:5000']
[2025-06-14T21:45:11.643+0100] {subprocess.py:86} INFO - Output:
[2025-06-14T21:45:11.649+0100] {subprocess.py:93} INFO - python: can't open file '/tmp/airflowtmpuzs7ypiv/../../scripts/model_training.py': [Errno 2] No such file or directory
[2025-06-14T21:45:11.650+0100] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-14T21:45:11.651+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-14T21:45:11.654+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-14T21:45:11.656+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=customer_churn_training_dag, task_id=train_small_dataset, run_id=manual__2025-06-14T20:40:07.071750+00:00, execution_date=20250614T204007, start_date=20250614T204511, end_date=20250614T204511
[2025-06-14T21:45:11.662+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task train_small_dataset (Bash command failed. The command returned a non-zero exit code 2.; 119031)
[2025-06-14T21:45:11.675+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-14T21:45:11.682+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-14T21:45:11.686+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
