[2025-06-14T22:02:16.612+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-14T22:02:16.617+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_on_small_dataset manual__2025-06-14T21:02:14.413275+00:00 [queued]>
[2025-06-14T22:02:16.620+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_on_small_dataset manual__2025-06-14T21:02:14.413275+00:00 [queued]>
[2025-06-14T22:02:16.620+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-14T22:02:16.628+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_on_small_dataset> on 2025-06-14 21:02:14.413275+00:00
[2025-06-14T22:02:16.631+0100] {standard_task_runner.py:64} INFO - Started process 127508 to run task
[2025-06-14T22:02:16.633+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_churn_training_dag', 'train_on_small_dataset', 'manual__2025-06-14T21:02:14.413275+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpagtyfk61']
[2025-06-14T22:02:16.634+0100] {standard_task_runner.py:91} INFO - Job 41: Subtask train_on_small_dataset
[2025-06-14T22:02:16.654+0100] {task_command.py:426} INFO - Running <TaskInstance: customer_churn_training_dag.train_on_small_dataset manual__2025-06-14T21:02:14.413275+00:00 [running]> on host neonm.
[2025-06-14T22:02:16.689+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_churn_training_dag' AIRFLOW_CTX_TASK_ID='train_on_small_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T21:02:14.413275+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T21:02:14.413275+00:00'
[2025-06-14T22:02:16.690+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-14T22:02:16.691+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-14T22:02:16.691+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /home/press/coding/acronis_interview_v02 &&             venv/bin/python scripts/model_training.py                 --data_path data/customer_churn_small.csv                 --n_estimators 50                 --max_depth 5                 --top_n_features 10                 --mlflow_tracking_uri http://127.0.0.1:5000\n        ']
[2025-06-14T22:02:16.694+0100] {subprocess.py:86} INFO - Output:
[2025-06-14T22:02:16.695+0100] {subprocess.py:93} INFO - /usr/bin/bash: line 2: venv/bin/python: No such file or directory
[2025-06-14T22:02:16.695+0100] {subprocess.py:97} INFO - Command exited with return code 127
[2025-06-14T22:02:16.695+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-14T22:02:16.698+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-06-14T22:02:16.699+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=customer_churn_training_dag, task_id=train_on_small_dataset, run_id=manual__2025-06-14T21:02:14.413275+00:00, execution_date=20250614T210214, start_date=20250614T210216, end_date=20250614T210216
[2025-06-14T22:02:16.706+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task train_on_small_dataset (Bash command failed. The command returned a non-zero exit code 127.; 127508)
[2025-06-14T22:02:16.725+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-14T22:02:16.732+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-14T22:02:16.735+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
