[2025-06-14T20:02:23.162+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-14T20:02:23.170+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_on_small_dataset manual__2025-06-14T19:02:21.382110+00:00 [queued]>
[2025-06-14T20:02:23.173+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_on_small_dataset manual__2025-06-14T19:02:21.382110+00:00 [queued]>
[2025-06-14T20:02:23.173+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-14T20:02:23.181+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_on_small_dataset> on 2025-06-14 19:02:21.382110+00:00
[2025-06-14T20:02:23.182+0100] {standard_task_runner.py:64} INFO - Started process 78253 to run task
[2025-06-14T20:02:23.184+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_churn_training_dag', 'train_on_small_dataset', 'manual__2025-06-14T19:02:21.382110+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpjt11iub1']
[2025-06-14T20:02:23.185+0100] {standard_task_runner.py:91} INFO - Job 9: Subtask train_on_small_dataset
[2025-06-14T20:02:23.206+0100] {task_command.py:426} INFO - Running <TaskInstance: customer_churn_training_dag.train_on_small_dataset manual__2025-06-14T19:02:21.382110+00:00 [running]> on host neonm.
[2025-06-14T20:02:23.238+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_churn_training_dag' AIRFLOW_CTX_TASK_ID='train_on_small_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T19:02:21.382110+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T19:02:21.382110+00:00'
[2025-06-14T20:02:23.239+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-14T20:02:23.239+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-14T20:02:23.240+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /acronis_interview_v02/scripts && python scripts/model_training.py --data_path data/customer_churn_small.csv --mlflow_tracking_uri http://localhost:5001']
[2025-06-14T20:02:23.243+0100] {subprocess.py:86} INFO - Output:
[2025-06-14T20:02:23.243+0100] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /acronis_interview_v02/scripts: No such file or directory
[2025-06-14T20:02:23.243+0100] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-14T20:02:23.243+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-14T20:02:23.246+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-14T20:02:23.247+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=customer_churn_training_dag, task_id=train_on_small_dataset, run_id=manual__2025-06-14T19:02:21.382110+00:00, execution_date=20250614T190221, start_date=20250614T190223, end_date=20250614T190223
[2025-06-14T20:02:23.253+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task train_on_small_dataset (Bash command failed. The command returned a non-zero exit code 1.; 78253)
[2025-06-14T20:02:23.276+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-14T20:02:23.285+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-14T20:02:23.288+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
