[2025-06-14T21:21:33.861+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-14T21:21:33.868+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:21:31.489393+00:00 [queued]>
[2025-06-14T21:21:33.870+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:21:31.489393+00:00 [queued]>
[2025-06-14T21:21:33.870+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-14T21:21:33.878+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_small_dataset> on 2025-06-14 20:21:31.489393+00:00
[2025-06-14T21:21:33.879+0100] {standard_task_runner.py:64} INFO - Started process 103789 to run task
[2025-06-14T21:21:33.881+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_churn_training_dag', 'train_small_dataset', 'manual__2025-06-14T20:21:31.489393+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpihz8sfw8']
[2025-06-14T21:21:33.881+0100] {standard_task_runner.py:91} INFO - Job 17: Subtask train_small_dataset
[2025-06-14T21:21:33.902+0100] {task_command.py:426} INFO - Running <TaskInstance: customer_churn_training_dag.train_small_dataset manual__2025-06-14T20:21:31.489393+00:00 [running]> on host neonm.
[2025-06-14T21:21:33.935+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_churn_training_dag' AIRFLOW_CTX_TASK_ID='train_small_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T20:21:31.489393+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T20:21:31.489393+00:00'
[2025-06-14T21:21:33.935+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-14T21:21:33.936+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-14T21:21:33.936+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /path/to/your/repo/train.py --dataset data/small_dataset.csv --n_estimators 150 --max_depth 8 --mlflow_uri http://127.0.0.1:5000']
[2025-06-14T21:21:33.939+0100] {subprocess.py:86} INFO - Output:
[2025-06-14T21:21:33.945+0100] {subprocess.py:93} INFO - python: can't open file '/path/to/your/repo/train.py': [Errno 2] No such file or directory
[2025-06-14T21:21:33.946+0100] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-14T21:21:33.947+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-14T21:21:33.950+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/press/miniconda3/envs/acronis/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-14T21:21:33.952+0100] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=customer_churn_training_dag, task_id=train_small_dataset, run_id=manual__2025-06-14T20:21:31.489393+00:00, execution_date=20250614T202131, start_date=20250614T202133, end_date=20250614T202133
[2025-06-14T21:21:33.958+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task train_small_dataset (Bash command failed. The command returned a non-zero exit code 2.; 103789)
[2025-06-14T21:21:33.973+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-06-14T21:21:33.981+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-14T21:21:33.982+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
